%YAML:1.0
---

enable_front: 1
enable_left: 0
enable_right: 0
enable_rear: 0
downsample_ratio: 1.0
use_vworks: 1
block_size: 9
min_disparity: 0
num_disp: 64
disp12Maxdiff: 32000
prefilterCap: 39
prefilterSize: 5
uniquenessRatio: 0
speckleWindowSize: 300
speckleRange: 5
mode: 1
p1: 100
p2: 200

bt_clip_value: 31
ct_win_size: 0
hc_win_size: 1
scanlines_mask: 255

pub_cloud_step: 3
show_disparity: 1
flags: 2