%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 600
image_height: 600
distortion_parameters:
   k1: 0
   k2: 0
   p1: 0
   p2: 0
projection_parameters:
   fx: 156.170115
   fy: 156.170115
   cx: 300
   cy: 300
